Repro composition error when built-in scalar is defined in subgraph
Error: `[subgraphA] Invalid default value (got: true) provided for argument @key(resolvable:) of type Boolean.`